### ISSUE TITLE
Deploy Asimba in its own tomcat container

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-Asimba#21]
We can't deal with this restart issue. We need to deploy Asimba in its own container.

**Comment by yurem** [comment]
I've merged Ganesh changes to setup: https://github.com/GluuFederation/community-edition-setup/pull/166

They should help to create second tomcat instance. Now according to [issue](https://github.com/GluuFederation/community-edition-setup/issues/115) we uses distribution archives instead of old approach with manually extracted and modified tomcat/jython.

**Comment by yurem** [comment]
We only change Asimba IDP/request pools/SP lists. Maybe we don't need full Asimba restart. What do you think about changing only these lists?

**Comment by dmogn** [comment]
Obsolete since 3.0.0 (jetty containers).
