### ISSUE TITLE
saml_script + Asimba = no selector

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-Asimba#28]
This is actually a question than issue. @dmogn @nynymike @yurem 
If we configure asimba with saml script; 'selector' feature lost it's usability.  Any thoughts or idea how we can manage asimba+saml_script along with 'selector' feature? 

As we can see in below screenshot, 

1. The list of RP selectors; only one.. the /saml one. 
2. In Selector section we can only point 'https://test.gluu.org/saml' to target IDP. 

Question is: if we want to configure 'sp2.gluu.org' --> 'https://2ndIDP.gluu.org'; how can we achieve that? 

![sp_requestor_list](https://cloud.githubusercontent.com/assets/7156097/18747014/7a223c38-8090-11e6-974c-20a32f011b60.png)

![sp_selector2](https://cloud.githubusercontent.com/assets/7156097/18747020/7ea80e4a-8090-11e6-8df5-b9467fbdb29a.png)

**Comment by yurem** [comment]
Here is our currnt workflow:
SP1 (sp1.gluu.org) or SP2 (sp2.gluu.org) → IDP (test.gluu.org) → oxAuth Saml script (test.gluu.org) → Asimba (test.gluu.org)....

We have this problem because script for all SP prepares request with same issuer. And there is no information in the script about initial SP because all of them calls same IDP.

Can we change workflow to:
SP1 (sp1.gluu.org) → IDP (sp1.gluu.org) → oxAuth Saml script (test.gluu.org) → ...
SP2 (sp2.gluu.org) → IDP (sp2.gluu.org) → oxAuth Saml script (test.gluu.org) → ...

?

In this case each SP will communicate with different IDPs. Hence each IDP will prepare Saml Request with different issuer.

**Comment by yurem** [comment]
Also as usual we have many variants to resolve one problem. This one still allow to use current workflow with one IDP. But it's requires some research and development. I think in IDP we can get initial SP name and pass it to oxAuth Saml script.

More details:
SP->IDP->oxAuth authorization request with origin=SP...->oxAuth->Saml script

As you can see in our patch to IDP we need to find origin and pass it to oxAuth.

Finally in Saml script based on origin we can build Saml request with right issuer.

**Comment by yurem** [comment]
First one e can do now. There is oen problem. It requires many IDP.
Second approach I can try to implement on Monday after finish OTP script.

Which approach is better? What do you think?

**Comment by mzico** [comment]
@yurem : 

>> First one we can do now. There is one problem. It requires many IDP.

Many IDP means? 

>> Second approach I can try to implement on Monday after finish OTP script.

Sure, it's not deadly urgent. 

My suggestion, do you think we can prepare something like 'issuerSP'? Then somewhere we can add this property for 'issuerSP --> target IDP'.

**Comment by nynymike** [comment]
In my opinion, there should be only one SP: oxAuth.
